// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMCV.Infrastructure.Data;

#nullable disable

namespace SMCV.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMCV.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResumeFileName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResumeFilePath")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("SMCV.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Position")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Email");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SMCV.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("SMCV.Domain.Entities.Contact", b =>
                {
                    b.HasOne("SMCV.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Contacts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("SMCV.Domain.Entities.EmailLog", b =>
                {
                    b.HasOne("SMCV.Domain.Entities.Contact", "Contact")
                        .WithOne("EmailLog")
                        .HasForeignKey("SMCV.Domain.Entities.EmailLog", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("SMCV.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("SMCV.Domain.Entities.Contact", b =>
                {
                    b.Navigation("EmailLog");
                });
#pragma warning restore 612, 618
        }
    }
}
